---

# This is the default hiera file
# Any parameters added here will be applied to every system
#
# Hiera crashes if there are empty files, so
# please remove the following line if you use this file
this_is_an_example_key: 'that does nothing'
simp_options::puppet::ca: 'puppet.simp.local'
simp_options::puppet::server: 'puppet.simp.local'
