---

# This is the default hiera file
# Any parameters added here will be applied to every system
#
# Hiera crashes if there are empty files, so
# please remove the following line if you use this file
this_is_an_example_key: 'that does nothing'
simp_options::puppet::ca : '172.28.128.3'
simp_options::puppet::ca_port : 8141
simp_options::puppet::server : '172.28.128.3'
simp_options::dns::servers :
  - '127.0.0.1'
  - '192.168.1.1'
